### ISSUE TITLE
Different graphics?

### ISSUE THREAD

**Issue by Pesegato** [riccardobl/FPSDEMO-jMonkeyEngine#1]
If I download the project and open the build.gradle with IntelliJ I get this:

![image](https://user-images.githubusercontent.com/8915763/95766569-bb8a1480-0cb3-11eb-82c5-cc9f90a1041d.png)

**Comment by riccardobl** [comment]
Ehm no, this is not the same demo. 
Your screenshot is from this one: https://github.com/jMonkeyEngine-Templates/simple-fps-shooter
Maybe you opened the wrong project, since they have similar names :man_shrugging:

**Comment by Pesegato** [comment]
Oh right, my bad
